// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX2BOC1RSoiNPPG1R7ch7PZhylr75XJiQ',
    appId: '1:225259713653:web:84733000cbcc6f2855f43c',
    messagingSenderId: '225259713653',
    projectId: 'greenland-cf638',
    authDomain: 'greenland-cf638.firebaseapp.com',
    storageBucket: 'greenland-cf638.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAghRoo_R7mqIc1fpCJ-Hxbi2f56RcBXc',
    appId: '1:225259713653:android:511f777d9302377455f43c',
    messagingSenderId: '225259713653',
    projectId: 'greenland-cf638',
    storageBucket: 'greenland-cf638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDoNBHLyPvey1ablQilIWQrZLb43FzI2k',
    appId: '1:225259713653:ios:c06d6633429b2cbf55f43c',
    messagingSenderId: '225259713653',
    projectId: 'greenland-cf638',
    storageBucket: 'greenland-cf638.appspot.com',
    iosBundleId: 'com.example.greenland',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDoNBHLyPvey1ablQilIWQrZLb43FzI2k',
    appId: '1:225259713653:ios:bc3be8e91898b12555f43c',
    messagingSenderId: '225259713653',
    projectId: 'greenland-cf638',
    storageBucket: 'greenland-cf638.appspot.com',
    iosBundleId: 'com.example.greenland.RunnerTests',
  );
}
